# -*- coding: utf-8 -*- This line is just for your information, the python plugin will not use the first line
insert into  "zz_gvflode"("typ","beskrivning") values ('huvudmag','huvudmagasinet');
insert into  "zz_gvflode"("typ","beskrivning") values ('jordlager','jordlager');
insert into  "zz_gvflode"("typ","beskrivning") values ('överlagrande magasin','överlagrande magasin');
insert into  "zz_gvflode"("typ","beskrivning") values ('ytliga jordlager','ytliga jordlager');
insert into  "zz_gvflode"("typ","beskrivning") values ('berg','berggrunden');
insert into  "zz_gvflode"("typ","beskrivning") values ('ospec','ospecificierat grundvattenflöde');
insert into  "zz_gvflode"("typ","beskrivning") values ('ytvatten','ytvatten');
insert into  "zz_gvdel"("typ","beskrivning") values ('fast','fast grundvattendelare');
insert into  "zz_gvdel"("typ","beskrivning") values ('rörlig','rörlig grundvattendelare');
insert into  "zz_gvdel"("typ","beskrivning") values ('stalp','stalp');
insert into  "zz_gvdel"("typ","beskrivning") values ('annan gräns','annan gräns');
insert into  "zz_gvmag"("typ","beskrivning") values ('huvudmag','huvudmagasin');
insert into  "zz_gvmag"("typ","beskrivning") values ('centralt','central del av huvudmagasinet');
insert into  "zz_gvmag"("typ","beskrivning") values ('perifert','perifer del av huvudmagasinet');
insert into  "zz_gvmag"("typ","beskrivning") values ('jordlager','magasin i jordlager');
insert into  "zz_gvmag"("typ","beskrivning") values ('överlagrande magasin','magasin i jordlager som överlagrar något annat magasin');
insert into  "zz_gvmag"("typ","beskrivning") values ('ytliga jordlager','magasin i ytliga jordlager');
insert into  "zz_gvmag"("typ","beskrivning") values ('berg','magasin i berggrunden');
insert into  "zz_gvmag"("typ","beskrivning") values ('möjligt','möjligt magasin');
insert into  "zz_tillromr"("typ","beskrivning") values ('a','typ a - hela gvbildn infiltrerar direkt till magasinet');
insert into  "zz_tillromr"("typ","beskrivning") values ('b','typ b - hela gvbildn når magasinet via något annat magasin');
insert into  "zz_tillromr"("typ","beskrivning") values ('c','typ c - delar av gvbildn når magasinet');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('spröd','spröd deformationszon');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('plastisk','plastisk deformtionszon');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('strukturell','strukturell formlinje (BYT TILL ANNAN. DENNA SKA TAS BORT)');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('kontakt','litologisk kontakt ((BYT TILL ANNAN. DENNA SKA TAS BORT)');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('ospec','ospecificerad strukturlinje');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('bergrygg','sammanhängande ryggformad struktur i berggrunden');
insert into  "zz_strukturlinje"("typ","beskrivning") values ('djupfåra','sammanhängande djupfåra/tråg i berggrunden');
insert into  "zz_trptid"("typ","beskrivning") values (1,'mkt kort tid (<1 d)');
insert into  "zz_trptid"("typ","beskrivning") values (2,'kort tid (1-10 d)');
insert into  "zz_trptid"("typ","beskrivning") values (3,'måttlig tid (10-100 d)');
insert into  "zz_trptid"("typ","beskrivning") values (4,'lång tid (100-1000 d)');
insert into  "zz_trptid"("typ","beskrivning") values (5,'mkt lång tid (1000-10 000 d)');
insert into  "zz_trptid"("typ","beskrivning") values (6,'extremt lång tid (>10 000 d)');
insert into  "zz_omattad_zon"("typ","beskrivning") values (0,'ospecificerad omättad zon');
insert into  "zz_omattad_zon"("typ","beskrivning") values (1,'mäktig omättad zon');
insert into  "zz_omattad_zon"("typ","beskrivning") values (2,'mkt liten omättad zon (<1 m)');
insert into  "zz_omattad_zon"("typ","beskrivning") values (3,'liten omättad zon (1-3 m)');
insert into  "zz_omattad_zon"("typ","beskrivning") values (4,'måttlig omättad zon (3-6 m)');
insert into  "zz_omattad_zon"("typ","beskrivning") values (5,'mäktig omättad zon (6-9 m)');
insert into  "zz_omattad_zon"("typ","beskrivning") values (6,'mkt mäktig omättad zon (>9 m)');

